version: '3.8'

services:
  # PostgreSQL Database for tests
  postgres-test:
    image: postgres:15-alpine
    container_name: test-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test  # pragma: allowlist secret
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mock OAuth2 Server for tests
  mock-oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    container_name: test-oauth2
    ports:
      - "8180:8080"  # Map to 8180 to avoid conflicts with Keycloak
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
      - JSON_CONFIG_PATH=/tmp/mock-oauth2-config.json
    volumes:
      - ./docker/mock-oauth2/config.json:/tmp/mock-oauth2-config.json:ro
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/default/.well-known/openid-configuration"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test-network:
    driver: bridge
    name: test-network