# Local Development Profile Configuration
spring:
  profiles:
    active: local
    
  jpa:
    hibernate:
      ddl-auto: update  # Auto-update schema in local development
    show-sql: true      # Show SQL queries in local
    
  graphql:
    graphiql:
      enabled: true     # Enable GraphiQL UI for local development

# Local OAuth2 configuration (Keycloak running in Docker)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

# Local database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/domain_template
    username: people_org_user
    password: dev_password_123  # pragma: allowlist secret

# Logging configuration for local development
logging:
  level:
    org.erp_microservices: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development-specific settings
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints in local
  endpoint:
    health:
      show-details: always
      show-components: always